import * as React from 'react';
import Head from 'next/head';
import Link from 'next/link';
import { sanityClient, urlFor } from '../../lib/sanity';

type Props = {
  recipes: Recipes[],
};

type Recipes = {
  _id: string,
  name: string,
  slug: string,
  mainImage: string,
}

const Home: React.FC<Props> = ({ recipes }) => (
  <div>
    <Head>
      <title>My Kitchen🙋‍♀️</title>
      <meta name="description" content="Generated by Next.js" />
    </Head>

    <h1>Welcome to My Kitchen🙋‍♀️</h1>

    <ul className='recipes-list'>
      {recipes?.length > 0 &&
        recipes.map((recipe) => (
          <li key={recipe._id} className='recipe-card'>
            <Link href="/">
              <a>
                <img src={urlFor(recipe.mainImage).url()} alt={recipe.name} />
                <span>{recipe.name}</span>
              </a>
            </Link>
          </li>
        ))
      }
    </ul>
  </div>
);

export const getStaticProps = async () => {
  const recipes = await sanityClient.fetch(recipesQuery);
  return {
    props: { recipes }
  };
};

const recipesQuery = `*[_type == "recipe"]{
  _id,
  name,
  slug,
  mainImage,
}`;

export default Home;
